name: Build and Push Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. GCP 인증
      - name: Setup GCP credentials
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      # 3. Docker 로그인 (gcloud credential helper 사용)sdds
      - name: Configure Docker with GCP
        run: |
          gcloud auth configure-docker asia-northeast3-docker.pkg.dev --quiet
          echo "== Docker credentials helper config =="
          cat ~/.docker/config.json   # Docker가 GCP credential helper를 등록했는지 확인


      # 5. Docker 이미지 빌드
      - name: Build Docker image
        run: |
          IMAGE=asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tomson-ai/tomson-ai:${{ github.sha }}
          echo "Building Docker image $IMAGE"
          docker build -t $IMAGE ./   # 로컬 디렉토리(./)를 빌드 컨텍스트로 사용

      # 6. Docker 이미지 푸시
      - name: Push Docker image
        run: |
          IMAGE=asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tomson-ai/tomson-ai:${{ github.sha }}
          echo "Pushing Docker image $IMAGE"
          docker push $IMAGE


      # 7. VM에 SSH 접속 후 컨테이너 재시작 s
      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tomson-ai/tomson-ai:latest
            docker stop tomson-ai || true
            docker rm tomson-ai || true
            docker run -d -p 8080:8080 \
              -e DB_URL="${{ secrets.DB_URL }}" \
              -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              --name tomson-ai \
              asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tomson-ai/tomson-ai:latest
